### ISSUE TITLE
How to mount on k8s config

### ISSUE THREAD

**Issue by Erchoc** [bitnami/bitnami-docker-blackbox-exporter#1]
> in test.yaml , how can I mount the container /etc/blackbox_exporter???

- you can try then answer me why don't have /etc/blackbox???

**Comment by javsalgar** [comment]
Hi,

As seen here: https://github.com/bitnami/bitnami-docker-blackbox-exporter#configuration
```
The default location for the config file is /opt/bitnami/blackbox-exporter/conf/config.yml, you can mount a volume there in order to overwrite it.


```

Would that work for you?
