### ISSUE TITLE
Incorrect config path in readme

### ISSUE THREAD

**Issue by gnarroway** [bitnami/bitnami-docker-blackbox-exporter#2]
**Description**

The docs state that the default config path is `/opt/bitnami/blackbox-exporter/conf/config.yml`. This appears to be incorrect. The actual default config path is `/opt/bitnami/blackbox-exporter/blackbox.yml`.

**Steps to reproduce the issue:**

1. Run the image as a shell `docker run -it --rm --entrypoint=/bin/bash bitnami/blackbox-exporter`
2. Look inside `/opt/bitnami/blackbox-exporter`

**Describe the results you received:**

- There is no `conf` dir, 
- there is a `blackbox.yml`, 
- `bin/blackbox_exporter --help` explicitly states the default config is `blackbox.yml`

**Describe the results you expected:**

The default conf to be where the readme said it would be (`/opt/bitnami/blackbox-exporter/conf/config.yml`)

**Additional information you deem important (e.g. issue happens only occasionally):**

- I don't think this image should try and alter the default config from upstream, so the best thing would probably be to fix the readme.
- Given the default config is now in a folder with other things in it, it is a bit more troublesome to mount custom config into it when using Kubernetes. Therefore, maybe the readme can advise mounting the config volume in the previous place (in a dedicated conf dir), and running it with an explicit command e.g. `/opt/bitnami/blackbox-exporter/bin/blackbox_exporter --config.file=/opt/bitnami/blackbox-exporter/conf/config.yml`

**Comment by rafariossaa** [comment]
Hi,
  Thanks for noticing this.
  Would you like to send a PR ? We will be glad to review and merge it.

**Comment by rafariossaa** [comment]
Maybe other solution could be to create a symbolic link: `config.yml --> config/config.yml`
This way the volume could be used to mount your own configuration.
